export default [
  {
    icon: "el-icon-user-solid",
    children: [],
    hasChildren: null,
    id: 1,
    keepAlive: "0",
    label: "示例页面",
    name: "示例页面",
    parentId: -1,
    path: "/examples",
    redirect: "/examples/index_one",
    permission: null,
    sort: 7,
    spread: false,
    type: "0",
    show: false,
    children: [
      {
        children: [],
        hasChildren: null,
        id: 101,
        keepAlive: "0",
        label: "普通页面",
        name: "普通页面",
        parentId: 1,
        path: "/examples/page_one",
        permission: null,
        sort: 7,
        spread: false,
        type: "0",
        show: false,
      },
      {
        children: [],
        hasChildren: null,
        id: 102,
        keepAlive: "0",
        label: "tree页面",
        name: "tree页面",
        parentId: 1,
        path: "/examples/page_two",
        permission: null,
        sort: 7,
        spread: false,
        type: "0",
        show: false,
      },
    ]
  },

  // {
  //   icon: "el-icon-user-solid",
  //   children: [],
  //   hasChildren: null,
  //   id: 4,
  //   keepAlive: "0",
  //   label: "权限管理",
  //   name: "权限管理",
  //   parentId: -1,
  //   path: "/power",
  //   redirect: "/power/menu/index",
  //   permission: null,
  //   sort: 7,
  //   spread: false,
  //   type: "0",
  //   show: false,
  //   children: [
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 401,
  //       keepAlive: "0",
  //       label: "菜单管理",
  //       name: "菜单管理",
  //       parentId: 4,
  //       path: "/power/menu/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 402,
  //       keepAlive: "0",
  //       label: "用户管理",
  //       name: "用户管理",
  //       parentId: 4,
  //       path: "/power/user/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 403,
  //       keepAlive: "0",
  //       label: "公司管理",
  //       name: "公司管理",
  //       parentId: 4,
  //       path: "/power/dept/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 404,
  //       keepAlive: "0",
  //       label: "角色管理",
  //       name: "角色管理",
  //       parentId: 4,
  //       path: "/power/role/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 405,
  //       keepAlive: "0",
  //       label: "小区管理",
  //       name: "小区管理",
  //       parentId: 4,
  //       path: "/power/area/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //   ]
  // },
  // {
  //   icon: "el-icon-user-solid",
  //   children: [],
  //   hasChildren: null,
  //   id: 5,
  //   keepAlive: "0",
  //   label: "系统管理",
  //   name: "系统管理",
  //   parentId: -1,
  //   path: "/admin",
  //   redirect: "/admin/log/index",
  //   permission: null,
  //   sort: 7,
  //   spread: false,
  //   type: "0",
  //   show: false,
  //   children: [
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 501,
  //       keepAlive: "0",
  //       label: "日志管理",
  //       name: "日志管理",
  //       parentId: 5,
  //       path: "/admin/log/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //     {
  //       children: [],
  //       hasChildren: null,
  //       id: 502,
  //       keepAlive: "0",
  //       label: "app管理",
  //       name: "app管理",
  //       parentId: 5,
  //       path: "/admin/app/index",
  //       permission: null,
  //       sort: 7,
  //       spread: false,
  //       type: "0",
  //       show: false,
  //     },
  //   ]
  // },

];
